<?php
ini_set('display_errors', 1);
error_reporting(E_ALL);
session_start();

if (!isset($_SESSION['admin_id'])) {
    header('Location: admin_login.php');
    exit;
}

require 'db.php';

if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
    header('Location: admin_reports.php');
    exit;
}

$month_str = $_POST['report_month'] ?? ''; // Format: 2026-01
$password = $_POST['password'] ?? '';

if (!$month_str || !$password) {
    header('Location: admin_reports.php?error=Missing required fields');
    exit;
}

try {
    // 1. Authenticate Admin Password
    $stmt = $pdo->prepare("SELECT password_hash FROM users WHERE id = ? AND is_admin = 1");
    $stmt->execute([$_SESSION['admin_id']]);
    $admin = $stmt->fetch();

    if (!$admin || !password_verify($password, $admin['password_hash'])) {
        header('Location: admin_reports.php?error=Incorrect Admin Password');
        exit;
    }

    // 2. Prepare Date Range
    $start_date = $month_str . '-01 00:00:00';
    $end_date = date('Y-m-t 23:59:59', strtotime($start_date));
    
    // 3. Gather Data
    
    // 3. Gather Data
    // Filter by Lot if applicable
    $lot_filter = "";
    $params = [$start_date, $end_date];
    
    if (isset($_SESSION['admin_lot_id']) && $_SESSION['admin_lot_id'] !== null) {
        $lot_filter = " AND s.lot_id = ?";
        $params[] = $_SESSION['admin_lot_id'];
    }

    // Summary Stats
    // Need to join slots for lot info
    $sql = "SELECT COUNT(*) FROM bookings b JOIN parking_slots s ON b.slot_id = s.id WHERE b.created_at BETWEEN ? AND ?" . $lot_filter;
    $total_bookings = $pdo->prepare($sql);
    $total_bookings->execute($params);
    $count_bookings = $total_bookings->fetchColumn();

    $sql = "SELECT COUNT(DISTINCT b.user_id) FROM bookings b JOIN parking_slots s ON b.slot_id = s.id WHERE b.created_at BETWEEN ? AND ?" . $lot_filter;
    $unique_users = $pdo->prepare($sql);
    $unique_users->execute($params);
    $count_users = $unique_users->fetchColumn();

    $sql = "SELECT COUNT(*), SUM(b.penalty) FROM bookings b JOIN parking_slots s ON b.slot_id = s.id WHERE b.status='active' AND b.end_time < NOW() AND b.created_at BETWEEN ? AND ?" . $lot_filter;
    $penalties = $pdo->prepare($sql);
    $penalties->execute($params);
    $penalty_res = $penalties->fetch();
    $count_penalties = $penalty_res[0];
    $total_penalty_amt = $penalty_res[1] ?? 0;

    // Daily Breakdown
    $sql = "
        SELECT DATE(b.created_at) as log_date, COUNT(*) as b_count 
        FROM bookings b 
        JOIN parking_slots s ON b.slot_id = s.id
        WHERE b.created_at BETWEEN ? AND ? 
        $lot_filter
        GROUP BY DATE(b.created_at) 
        ORDER BY log_date ASC
    ";
    $daily = $pdo->prepare($sql);
    $daily->execute($params);
    $daily_data = $daily->fetchAll();

    // Top Users Analysis
    $sql = "
        SELECT u.name, u.email, COUNT(b.id) as booking_count 
        FROM bookings b 
        JOIN users u ON b.user_id = u.id 
        JOIN parking_slots s ON b.slot_id = s.id
        WHERE b.created_at BETWEEN ? AND ? 
        $lot_filter
        GROUP BY b.user_id 
        ORDER BY booking_count DESC 
        LIMIT 10
    ";
    $top_users = $pdo->prepare($sql);
    $top_users->execute($params);
    $top_users_data = $top_users->fetchAll();


    // 4. Generate CSV
    $filename = "astraea_report_" . $month_str . ".csv";
    
    header('Content-Type: text/csv');
    header('Content-Disposition: attachment; filename="' . $filename . '"');
    
    $output = fopen('php://output', 'w');
    
    // Header
    fputcsv($output, ['ASTRAEA PARKING ANALYSIS REPORT']);
    fputcsv($output, ['Report Month', $month_str]);
    fputcsv($output, ['Generated By', $_SESSION['admin_name']]);
    fputcsv($output, ['Generated At', date('Y-m-d H:i:s')]);
    fputcsv($output, []); // Blank line
    
    // Section 1: Executive Summary
    fputcsv($output, ['EXECUTIVE SUMMARY']);
    fputcsv($output, ['Metric', 'Value']);
    fputcsv($output, ['Total Bookings', $count_bookings]);
    fputcsv($output, ['Active Users (Unique)', $count_users]);
    fputcsv($output, ['Overdue Incidents', $count_penalties]);
    fputcsv($output, ['Total Penalty Assessed', 'INR ' . number_format($total_penalty_amt, 2)]);
    fputcsv($output, []); // Blank line

    // Section 2: Daily Trends
    fputcsv($output, ['DAILY BOOKING TRENDS']);
    fputcsv($output, ['Date', 'Total Bookings']);
    foreach ($daily_data as $row) {
        fputcsv($output, [$row['log_date'], $row['b_count']]);
    }
    fputcsv($output, []); // Blank line

    // Section 3: Top Users
    fputcsv($output, ['TOP CUSTOMERS']);
    fputcsv($output, ['Name', 'Email', 'Bookings']);
    foreach ($top_users_data as $row) {
        fputcsv($output, [$row['name'], $row['email'], $row['booking_count']]);
    }
    fputcsv($output, []); // Blank line

    // Section 4: Customer Reviews
    // Fetch reviews for the period
    $sql = "
        SELECT r.rating, r.review_text, b.created_at, u.name 
        FROM reviews r
        JOIN bookings b ON r.booking_id = b.id
        JOIN users u ON b.user_id = u.id
        JOIN parking_slots s ON b.slot_id = s.id
        WHERE b.created_at BETWEEN ? AND ?
        $lot_filter
        ORDER BY r.created_at DESC
    ";
    $reviews_stmt = $pdo->prepare($sql);
    $reviews_stmt->execute($params);
    $reviews_data = $reviews_stmt->fetchAll();

    if (count($reviews_data) > 0) {
        fputcsv($output, ['CUSTOMER REVIEWS']);
        fputcsv($output, ['Date', 'User', 'Rating', 'Comment']);
        
        $total_stars = 0;
        foreach ($reviews_data as $rev) {
            fputcsv($output, [
                date('Y-m-d H:i', strtotime($rev['created_at'])),
                $rev['name'],
                $rev['rating'] . ' / 5',
                $rev['review_text']
            ]);
            $total_stars += $rev['rating'];
        }
        
        // Add Average Logic to Summary if needed, or just leave as raw list
        $avg_rating = count($reviews_data) > 0 ? round($total_stars / count($reviews_data), 2) : 0;
        fputcsv($output, []);
        fputcsv($output, ['Average Rating for Period', $avg_rating]);
    }

    fclose($output);
    exit;

} catch (Exception $e) {
    header('Location: admin_reports.php?error=Report Generation Failed: ' . urlencode($e->getMessage()));
    exit;
}
